### ISSUE TITLE
Request: Support `categories:in`

### ISSUE THREAD

**Issue by duhduhdan** [bigcommerce/storefront-data-hooks#10]
It would be nice if GraphQL endpoint supported `categories:in` like the REST API does. I would expect to be able to do something like the following with this feature (ignoring your existing `edges` and `nodes` structure):

```gql
query {
  site {
    categoriesIn(entityIds: [1, 9, 4]) {
      products {
        id
        name
      }
  }
}
```
or, more reflective of the existing structure
```gql
query {
  site {
    products(categoriesIn: [1, 9, 4]) {
      // etc
    }
  }
}
```

With this we could have a more robust `useSearch` hook that allows you to pass in multiple `categoryId` for advanced filtering patterns.

**Comment by kfroemming** [comment]
This would be awesome.

**Comment by jorgemasta** [comment]
Hey @duhduhdan,
GraphQL's team has reported that this isn't on the roadmap currently, but they have created requests for this and are going to work on prioritizing it appropriately.

I am closing this ticket as it isn't something that depends on this repo.
