### ISSUE TITLE
includeProducts in useWishlist() - not updating the data items after add/remove

### ISSUE THREAD

**Issue by heylols** [bigcommerce/storefront-data-hooks#108]
Previously I opened the ticket where the Wishlist does not contain the products : https://github.com/bigcommerce/storefront-data-hooks/issues/103

Right now, the issue is if I add or remove items in the wishlist, the items returned are not updating. 

Eg:
```
const { data } = useWishlist({includeProducts : true })
console.log('included', data?.items)
// the items will not get updated after a adding/removing item to wishlist
```

But if I do not include the `includeProducts` parameter, the items are updating.

Eg:

```
const { data } = useWishlist()
console.log('included', data?.items)
// here items are seems to be updating
```

**Comment by jorgemasta** [comment]
Hey @heylols ,

this is similar to #89. We're using `swr` under the hook and `useWishlist({includeProducts : true })` uses a different key than `useWishlist()`.

When you use `useAddItem()` you're using the key used in `useWishlist()`.
You have to use `useAddItem({includeProducts : true })` to update `useWishlist({includeProducts : true })`

**Comment by heylols** [comment]
> useWishlist({includeProducts : true })

Thanks mate!
