### ISSUE TITLE
v1.8.0 not published to npm

### ISSUE THREAD

**Issue by leffot** [bigcommerce/storefront-data-hooks#139]
It looks like v1.8.0 was published here back in February, but the latest version on npm is still v1.7.0. Is there any way for v1.8.0 to be published?

**Comment by leffot** [comment]
Checking in on this, @chanceaclark

**Comment by chanceaclark** [comment]
Hey @leffot, let me see what I can do this week. Might need to revert some PR's before we can.

**Comment by Wkasel** [comment]
Hi Checking in on this.

**Comment by chanceaclark** [comment]
Went ahead and released it. Let me know if y'all run into any issues with the new version as some of the build stuff/commit/changelogs were a bit off.
