### ISSUE TITLE
Missing Reset password hook

### ISSUE THREAD

**Issue by MatixYo** [bigcommerce/storefront-data-hooks#14]
Currently there's no way to reset password using these hooks.

**Comment by magicspon** [comment]
I can't see anything in the bigcommerce api docs about resetting passwords... any pointers?

**Comment by jorgemasta** [comment]
There are a couple of options for resetting a user’s password:

1.)  https://developer.bigcommerce.com/api-reference/store-management/customers-v3/customers/customersput  `force_password_reset` set to `true` will trigger an email to be sent to the customer to reset their password

2.) You can post to https://store-<store_hash>-<channel_id>.mybigcommerce.com/login.php?action=send_password_email for the appropriate channel and this will send the right email with the correct links. (Watch out for CORS)

**Comment by andrewf414** [comment]
FYI options 1 doesn't seem to be quite enough to trigger the email, you have to attempt login. So I just did that and then did the useLogin hook with a phony password to trigger the email. The problem now is the email is something we have no control over and the link is to /login.php?action=change_password&c=<customerId>&t=<someToken>. So not sure how that gels with a headless app...

**Comment by kogan007** [comment]
> FYI options 1 doesn't seem to be quite enough to trigger the email, you have to attempt login. So I just did that and then did the useLogin hook with a phony password to trigger the email. The problem now is the email is something we have no control over and the link is to /login.php?action=change_password&c=&t=. So not sure how that gels with a headless app...

You can try syncing bigcommerce login with something like firebase and then if someone successfuly resets their password with firebase use the bigcommerce api to change the password.

**Comment by jorgemasta** [comment]
> > FYI options 1 doesn't seem to be quite enough to trigger the email, you have to attempt login. So I just did that and then did the useLogin hook with a phony password to trigger the email. The problem now is the email is something we have no control over and the link is to /login.php?action=change_password&c=&t=. So not sure how that gels with a headless app...
> 
> You can try syncing bigcommerce login with something like firebase and then if someone successfuly resets their password with firebase use the bigcommerce api to change the password.

Yes, thats seems to be a good workaround as BC doesn't support password reset through its API at the moment and this package support [SSO Login](https://github.com/bigcommerce/storefront-data-hooks/tree/28634a38dd08756e234d5609b695d73653cd7ddb#login-sso).

I am closing this ticket until further news from the BC API.
