### ISSUE TITLE
Confused which package to install

### ISSUE THREAD

**Issue by ricokahler** [bigcommerce/storefront-data-hooks#17]
[The current readme](https://github.com/bigcommerce/storefront-data-hooks/tree/93505ddeec9a7096c38cad247b8f3e966ed5276f) says to install `storefront-data-hooks` but all the packages are importing `@bigcommerce/storefront-data-hooks`.

Both packages are published to npm. Which one should I use?

**Comment by jorgemasta** [comment]
The correct one is @bigcommerce/storefront-data-hooks.
