### ISSUE TITLE
Getting error ./node_modules/@zeit/dns-cached-resolve/lib/dns-resolve.js:6:0

### ISSUE THREAD

**Issue by thebakerdev** [bigcommerce/storefront-data-hooks#18]
I'm trying to use this package in my nextjs project. When importing `import { getConfig } from '@bigcommerce/storefront-data-hooks/api'` I'm getting a `Module not found: Can't resolve 'dns'`.

Is there any dependency that I need to install? 

Here's my package.json
`
 "dependencies": {
    "@bigcommerce/storefront-data-hooks": "^1.0.2",
    "@contentful/rich-text-react-renderer": "14.1.1",
    "@splidejs/splide": "^2.4.21",
    "@splidejs/splide-extension-grid": "^0.2.0",
    "classnames": "2.2.6",
    "date-fns": "2.14.0",
    "i": "^0.3.6",
    "next": "latest",
    "npm": "^6.14.9",
    "prop-types": "^15.7.2",
    "react": "^16.13.1",
    "react-collapse": "^5.1.0",
    "react-dom": "^16.13.1",
    "react-modal": "^3.12.1"
  },
  "devDependencies": {
    "@fullhuman/postcss-purgecss": "^2.3.0",
    "@tailwindcss/aspect-ratio": "^0.2.0",
    "@types/react": "^17.0.0",
    "autoprefixer": "^10.0.4",
    "contentful-import": "^7.8.7",
    "postcss": "^8.1.10",
    "postcss-import": "^13.0.0",
    "postcss-nested": "^5.0.2",
    "postcss-preset-env": "^6.7.0",
    "tailwindcss": "^1.9"
  },
  "license": "MIT"

`

**Comment by jorgemasta** [comment]
Hey @thebakerdev, are you still having this issue?
If so, can you share which version of `npm`,  `yarn` and `node` you are using?

**Comment by avisra** [comment]
I just experienced this issue as well. I tried both with npm (6.14.9) and yarn (1.22.10). node (14.15.3)

**Comment by jorgemasta** [comment]
Can you show me the output of `yarn list --pattern @vercel/fetch`? It seems that this dependency is not installed

**Comment by avisra** [comment]
Hey all - I managed to track this issue down to a misunderstanding on my side. I saw this error if I had a error in the code. Specifically noticed it when trying to use some of the API operations client-side. If I moved them to server-side, it worked fine.

**Comment by jorgemasta** [comment]
Cool! Thank you very much for letting us know 🙌
