### ISSUE TITLE
Get custom product fields

### ISSUE THREAD

**Issue by Bryceacampbell** [bigcommerce/storefront-data-hooks#19]
Hello Team,

It seems products are NOT returning custom product fields set in big commerce. Any ideas how to accomplish this? I would like to display these on our dynamic products page

**Comment by zeekrey** [comment]
The `getProduct` method allows you to use a custom GraphQL query if assigned to the `query` key like so:

```
const { product } = await getProduct({
    query: 'here goes a GraphQL query string',
    variables: { slug: params!.slug },
    config,
    preview,
  });
```

As the [BigCommerce GraphQL expolorer](https://developer.bigcommerce.com/graphql-explorer) shows, the product field has a customFields field. With it you should be able to get your custom fields. Couldn't try it yet though.

**Comment by jorgemasta** [comment]
Hey @Bryceacampbell.  I agree with @zeekrey , if you want other data you can use your own query. Let me know if you need help generating it.

Related to #7
