### ISSUE TITLE
How do I add a product that doesn't have variants?

### ISSUE THREAD

**Issue by ricokahler** [bigcommerce/storefront-data-hooks#21]
Looking at the typescript types for `useAddItem`, it doesn't seem like there is a way to add items to the cart that don't have a variant.

How do I do this?

**Comment by amckemie** [comment]
@jivewise Can you help provide some insight on this question? Thanks!

**Comment by jivewise** [comment]
@ricokahler I believe the `ItemBody` declaration will need to be updated here: https://github.com/bigcommerce/storefront-data-hooks/blob/master/src/api/cart/index.ts#L17 to be optional.

I will work with @amckemie to make a PR for that soon, or you can feel free to do so if you have the time!

**Comment by jorgemasta** [comment]
The `variantId` should be optional.
> If a product has modifiers, omit the variant_id and instead use the option_selections array to describe both the variant and the modifier selections
> [Documentation](https://developer.bigcommerce.com/api-reference/store-management/carts/cart-items/addcartlineitem)

**Comment by jorgemasta** [comment]
It will be included in the next release
