### ISSUE TITLE
500 on updateItem when productId and variantId are missing

### ISSUE THREAD

**Issue by ricokahler** [bigcommerce/storefront-data-hooks#22]
[From the README](https://github.com/bigcommerce/storefront-data-hooks/tree/f1be99f00f68c8c23e17e5ac0d7f1fa0e4ad4f8d#useupdateitem), it seems like `updateItme` does not require the `productId` or the `variantId` when updating the quantity however I can't get this to work unless I include those.

```js
// this is the example copied from the README
import useUpdateItem from '@bigcommerce/storefront-data-hooks/cart/use-update-item'

const CartItem = ({ item }) => {
  const [quantity, setQuantity] = useState(item.quantity)
  // I ensured that `id`, `productId`, and `variantId` are present in here
  //                                👇 
  const updateItem = useUpdateItem(item)
  
  const updateQuantity = async (e) => {
    const val = e.target.value
    // 👋 this code does not work for me
    // this only seems to work if `productId` and `variantId` are present
    await updateItem({ quantity: val })
  }

  return (
    <input
      type="number"
      max={99}
      min={0}
      value={quantity}
      onChange={updateQuantity}
    />
  )
}
```

Is this a bug?

**Comment by jorgemasta** [comment]
Yes, there is a bug here: https://github.com/bigcommerce/storefront-data-hooks/blob/034be1e4c7fa363f4b1362fd1a6d50e25b2632ea/src/cart/use-update-item.tsx#L54

I will fix it today! Thanks for reporting it.

**Comment by jorgemasta** [comment]
It will be included in the next release
