### ISSUE TITLE
add videos and/or condition to GraphQL

### ISSUE THREAD

**Issue by eclipse3161** [bigcommerce/storefront-data-hooks#27]
Hi

We Building our Headless solution for our site fusionelectronix.com using vercel. we are facing an issue with GraphQL not have ability to query product data  specifically Product condition and Product video, it will great if this Enhancement to GraphQL Explorer
Thank you

**Comment by jorgemasta** [comment]
Hey @eclipse3161,
GraphQL's team has reported that these items are not on the roadmap currently, but they have created requests for this and are going to work on prioritizing it appropriately.

I am closing this ticket as it is not something that depends on this repo.
