### ISSUE TITLE
Can't install v1.0.3 vie npm pkg manager 

### ISSUE THREAD

**Issue by hghodasara** [bigcommerce/storefront-data-hooks#31]
I see on GitHub there v 1.0.3 is the latest released but when I try to install this version from npm 
using - `npm install @bigcommerce/storefront-data-hooks@1.0.3 --save` it not found

The issue is  SHOP_TOKEN cookie is not worked on v1.0.2 pkg,  

@amckemie can you please check this

**Comment by jorgemasta** [comment]
It will be included in the next release
