### ISSUE TITLE
Keep user logged in at checkout

### ISSUE THREAD

**Issue by jorgemasta** [bigcommerce/storefront-data-hooks#36]
Based on this comment: https://github.com/bigcommerce/storefront-data-hooks/issues/11#issuecomment-784794465

After logging in (and revalidating the customer) - going to checkout (redirects to bigcommerce checkout page - e.g. same as what Vercel commerce is doing) the user is not logged in - it is displaying guest checkout and has the option for user to login there. I would expect that the BC checkout page would know who the user is. I notice that the Vercel demo store has this same experience (when going to checkout, the user is not logged in). IMO, this defeats the purpose of the login.

**Comment by avisra** [comment]
Hey all,

I actually managed to solve this myself. I'm not sure why Vercel hasn't done a similar thing with their demo store. And ideally, this workaround wouldn't be necessary (I would rather be able to authenticate the checkout without sharing cookies).

Instead of using the default BigCommerce store URL, I setup a url like checkout.mywebsite.com. And my headless shop is www.mywebsite.com. In my code which creates the SHOP_TOKEN cookie, I updated the cookie to be a TLD cookie (e.g. forced it to create the cookie for mywebsite.com). After doing this, the checkout process was aware of the signed in user.

Thanks,

Chris

**Comment by jorgemasta** [comment]
That's very clever @avisra 👏
So, to confirm, this is your flow:
1. Customer login and add the items to the cart in your headless shop https://mywebsite.com
2. Customer press on "Proceed to checkout" and is redirected to https://checkout.mywebsite.com/checkout

I think this pattern is the only one that would work right now. The other alternative is the embedded checkout #6, although we would also have to do something similar with the domains but we don't have to share the cookie.

**Comment by jorgemasta** [comment]
Hey @avisra, I have been able to use the embedded checkout and share the cookie in this example: https://testenv.club/

Looks working properly but I don't know what you mean here https://github.com/bigcommerce/storefront-data-hooks/issues/11#issuecomment-791551322 by:

> Second - and this one is unfortunate - but BigCommerce has a weird quirk where it will attempt to create a new shop_session_token even though one exists already at the TLD. The first time it does this, it will be the correct value - but on the shop.mysite.com domain. **The second time it does this, it will be a different value and it won't work (use will be guest).**

I have not been able to replicate that in my example.

**Comment by magicspon** [comment]
@jorgemasta 
I'm using the latest release, with the embedded checkout. (setup as per the docs)
The checkout is loading as expected, but the user is logged out. See video below.
I'm also using the new SSO login method.

https://user-images.githubusercontent.com/3268717/112315230-d7053c80-8ca1-11eb-9513-57cd6b781c00.mp4

**Comment by jorgemasta** [comment]
> @jorgemasta
> I'm using the latest release, with the embedded checkout. (setup as per the docs)
> The checkout is loading as expected, but the user is logged out. See video below.
> I'm also using the new SSO login method.
> 
>  Kapture.2021-03-24.at.13.05.09.mp4

Hey @magicspon ,
Since you're using SSO Login, you have to take care of setting the `SHOP_TOKEN` at TLD (Top Level Domain) so that the checkout (which loads in an iframe on a subdomain) can access the token.

I have updated the [SSO Login gist](https://gist.github.com/jorgemasta/c709b63501344970026f3a3e7646cc77#file-sso-login-ts-L48-L50).

Let me know if it's works 😉

**Comment by magicspon** [comment]
Heyo... thanks for the quick response.
Alas, that's still not working

the cookie is now: 
```
SHOP_TOKEN=7fb203904d1fa72b0c6892e6189258028036b3da56c25f4bab9bedfe85869620_1617198232; expires=Wed, 31-Mar-2021 13:43:52 GMT; path=/; Secure; HttpOnly; SameSite=none; Domain=oomphgo.com
```

**Comment by magicspon** [comment]
The only difference with my code is this:

```
res.setHeader("Set-Cookie", [
	concatHeader(res.getHeader("Set-Cookie"), shopToken),
	serialize("token", response.authenticate.jwt, options), // tokens from craft graphql auth
	serialize("refresh", response.authenticate.refreshToken, options), // tokens from craft graphql auth
])
```

**Comment by magicspon** [comment]
the same thing happens when using the regular login hook without sso

**Comment by magicspon** [comment]
oooh progress... i just removed all the cookies on the checkout url, and the main url.
logged back in... 
![image](https://user-images.githubusercontent.com/3268717/112330556-0b7ff500-8cb0-11eb-8037-140f7837c789.png)

**Comment by jorgemasta** [comment]
Cool, thanks for replying back!
Changing from one way of saving the cookie to another probably has intermediate states that are not covered.
