### ISSUE TITLE
Get Product Options Rules

### ISSUE THREAD

**Issue by aganglada** [bigcommerce/storefront-data-hooks#43]
Hello team! 
I wen't through the code and it doesn't seem to be a way to get Product Options rules.

The ones specified in each product here:

<img width="995" alt="Screenshot 2021-03-10 at 10 45 53" src="https://user-images.githubusercontent.com/922348/110623032-2ae92f00-8194-11eb-9794-850722ebcedf.png">

There is a way to get Product Options, which is already working from the playground:

![Screenshot 2021-03-10 at 10 47 38](https://user-images.githubusercontent.com/922348/110623102-46ecd080-8194-11eb-8316-6a700eefc5b7.png)

But not the rules values.

Can I get your knowledge on how we could leverage this from any of your APIs.

Thank you in advance.

**Comment by jorgemasta** [comment]
Hey @aganglada,

Nice catch, the GraphQL's team equipment has been reported. They will work on prioritizing it correctly.

I am closing this ticket as it isn't something that depends on this repo.

**Comment by aganglada** [comment]
@jorgemasta could you confirm is not on the storefront api either? or is there a way to access it.

**Comment by arjanc** [comment]
Hi,
This 'feature' still isn't exposed in the GraphQL endpoint.
I hope it will be in the near future. Now I am forced to use the REST API.

For the people still looking for a solution...you will find a parameter value called 'adjusters' from this endpoint.
https://developer.bigcommerce.com/api-reference/c799ca0742d1b-get-all-product-modifiers
