### ISSUE TITLE
This product has options, variant ID is required

### ISSUE THREAD

**Issue by zeekrey** [bigcommerce/storefront-data-hooks#44]
Hey there,

I'm using the `useAddItem()` hook like this:

```typescript
const addItem = useAddItem();
await addItem({
        productId: product.entityId,
        variantId: getCurrentVariant(product, choices)?.node.entityId!,
      });
```

The cart object looks like the following:

![image](https://user-images.githubusercontent.com/34539149/110634345-2465b200-81aa-11eb-820c-b18c514ef3cb.png)

But when I try to use the checkout endpoints like `https://api.bigcommerce.com/stores/wm5qmanqs7/v3/checkouts/${body.cartId}/` I receive the following answer:

```json
'{"status":422,
"title":"Missing or incorrect required fields",
"type":"https://developer.bigcommerce.com/api-docs/getting-started/api-status-codes",
"errors":{"variant":"This product has options, variant ID is required"}}'
```

**Comment by jorgemasta** [comment]
I'm not sure if this a problem with this package since the cart creation looks ok.

Have you tried this in other env (postman, the api reference...)?

**Comment by zeekrey** [comment]
Yep, sorry. You're right. There is an issue with the customFields during checkout creation (https://github.com/bigcommerce/dev-docs/issues/1013). Should have checked the API first. Sorry 🥰
