### ISSUE TITLE
AddItem to a non-valid cart_id

### ISSUE THREAD

**Issue by dy-byron** [bigcommerce/storefront-data-hooks#49]
Somehow my cart_id got invalid. So every time I was trying to use the `useAddItem` hook, it gives me an error. 
I couldn't do anything else until I clean up all the cookies. 

To solve the problem on production, I did the following:
<img width="1223" alt="Screenshot 2021-03-23 at 15 59 27" src="https://user-images.githubusercontent.com/60141229/112167621-e24c5f80-8bf0-11eb-96dd-512cdd584413.png">
_/src/api/cart/handlers/add-item.ts_

It was a quick patch, so I was wondering if there is a better way to do this since it feels a little bit hacky. 

PS: Droping the whole file if it helps _/src/api/cart/handlers/add-item.ts_
```javascript
import { parseCartItem } from '../../utils/parse-item'
import getCartCookie from '../../utils/get-cart-cookie'
import type { CartHandlers } from '..'

// Return current cart info
const addItem: CartHandlers['addItem'] = async ({
  res,
  body: { cartId, item },
  config,
}) => {
  if (!item) {
    return res.status(400).json({
      data: null,
      errors: [{ message: 'Missing item' }],
    })
  }
  if (!item.quantity) item.quantity = 1

  const options = {
    method: 'POST',
    body: JSON.stringify({
      line_items: [parseCartItem(item)],
      ...(!cartId && config.storeChannelId
        ? { channel_id: config.storeChannelId }
        : {}),
    }),
  }

  let _data = null

  if (cartId) {
    try {
      const { data } = await config.storeApiFetch(`/v3/carts/${cartId}/items`, options)
      _data = data
    } catch {
      const { data } = await config.storeApiFetch('/v3/carts', options)
      _data = data
    }
  } else {
    const { data } = await config.storeApiFetch('/v3/carts', options)
    _data = data
  }

  // Create or update the cart cookie
  res.setHeader(
    'Set-Cookie',
    getCartCookie(config.cartCookie, _data.id, config.cartCookieMaxAge)
  )
  res.status(200).json({ data: _data })
}

export default addItem

```

**Comment by jorgemasta** [comment]
@dy-byron  Can you share the error that you're getting? Is it a 404?

If so, the cart cookie should be removed when you try to get the cart.
https://github.com/bigcommerce/storefront-data-hooks/blob/262164c80953060d59cf58129962b507cfb2a63c/src/api/cart/handlers/get-cart.ts#L16-L22

Anyway, it's probably a good idea to add that logic in the `add-item` as well.

Thanks for creating the issue! 🙌

**Comment by dy-byron** [comment]
@jorgemasta  When the `get-cart.ts` it's called, it does not throw an error nor 404. Instead goes to https://github.com/bigcommerce/storefront-data-hooks/blob/262164c80953060d59cf58129962b507cfb2a63c/src/api/cart/handlers/get-cart.ts#L26

So I got a cart with a `null` value with no errors. It's like Bigcommerce found the cart but with no data 🤷‍♂️

The error happens when I'm trying to add an item with this "non-valid cart_id" here https://github.com/bigcommerce/storefront-data-hooks/blob/262164c80953060d59cf58129962b507cfb2a63c/src/api/cart/handlers/add-item.ts#L25-L27

Which I believe is handled here
https://github.com/bigcommerce/storefront-data-hooks/blob/262164c80953060d59cf58129962b507cfb2a63c/src/api/cart/index.ts#L96-L104

I remember that the final error I'm getting in the frontend is a 500. 

Please let me know if I can do something else to help ✋

**Comment by avisra** [comment]
I've also run into this bug. I assume that BC carts expire or something - because it only happens after awhile. I'll customize my local copy of the data hooks. thanks yall - looking forward to a official fix :)

**Comment by jorgemasta** [comment]
Yes, I have created a PR fixing this #60 .
I should be released next week

**Comment by jorgemasta** [comment]
Released
