### ISSUE TITLE
An unexpected error ocurred with the Bigcommerce API

### ISSUE THREAD

**Issue by RobyCigar** [bigcommerce/storefront-data-hooks#55]
I deployed my site on vercel then, I try to sign up on my site

then when i sign up it gives me this error 
![image](https://user-images.githubusercontent.com/69680330/112742813-ff4fac80-8fbb-11eb-800c-3035e9c9a8de.png)

here's my site https://million-candles.vercel.app/

**Comment by magicspon** [comment]
Probably due to the graph token expiring.

**Comment by ahmadsyed** [comment]
Check if you have enabled store-front from the bigcommerce admin panel.
