### ISSUE TITLE
Related products

### ISSUE THREAD

**Issue by emilkowalski** [bigcommerce/storefront-data-hooks#7]
Is there a way to get related products with the getAllProducts hook?

**Comment by jorgemasta** [comment]
Hey @emilkowalski , you can use a custom GraphQL query to get the related products.

```js
const { products: allProducts } = await getAllProducts({
  query: customGetAllProductsQuery,
  config,
  preview,
})
```

Here an example of the query could looks like: https://gist.github.com/jorgemasta/fc5b29c59bd66d26ce3d28c1b71130b3
