### ISSUE TITLE
get product - not receiving default variant option from api

### ISSUE THREAD

**Issue by rahulguptacs1** [bigcommerce/storefront-data-hooks#76]
when variant option set to swatch we are receiving "isDefault" value properly
node: {label: "first", isDefault: true, hexColors: Array(1)}
but when using other options like rectangle or dropdown "isDefault" is not set
node: {label: "rahul"}

**Comment by jorgemasta** [comment]
Where are you setting variant option to swatch? 🤔 
Can you write the request and response in each case?

**Comment by jorgemasta** [comment]
Now I understand what you mean. It's something we can easily fix, we have to add `isRequired` after `displayName`. 
In this way it is accessible to all variants.

https://github.com/bigcommerce/storefront-data-hooks/blob/517a65789c4c8a09daa7add3068e010c79a179d0/src/api/fragments/product.ts#L78-L86

Thanks for opening this issue @rahulguptacs1! It will be fixed soon

**Comment by jorgemasta** [comment]
It will be released in `1.6.0`
