### ISSUE TITLE
getProduct - not receiving specific variant option type  (only "MultipleChoiceOption")

### ISSUE THREAD

**Issue by rahulguptacs1** [bigcommerce/storefront-data-hooks#77]
on backend we can set variant option type as rectangle, dropdown, swatch, radio
but  "__typename" property  is always set to "MultipleChoiceOption" and not the specific type we specified
how can we get it?

**Comment by jorgemasta** [comment]
Hi @rahulguptacs1, here is where we're asking for product variants:
https://github.com/bigcommerce/storefront-data-hooks/blob/517a65789c4c8a09daa7add3068e010c79a179d0/src/api/fragments/product.ts#L66-L76

As you see, you should receive an array of the variants with the `entityId` and the `defaultImage` of each one.

Can you write what you are receiving?

**Comment by jorgemasta** [comment]
I have come to understand what you mean. And you are right, there is no way to differentiate between the different types. It's a behaviour that is inherited from the API and that this package cannot change, so I'm closing this issue.
