### ISSUE TITLE
Feature Request:  getProducts hook that allows you to send multiple entity ID's

### ISSUE THREAD

**Issue by kfroemming** [bigcommerce/storefront-data-hooks#9]
Hey team, love what you guys are doing. I would like to submit a feature request that would allow for a developer to query a list of products. If you do not have the time, any guidance on making this addition myself would be helpful. I will post my code below and the questions I have associated with it.

```
// This is my proposal for products.ts

// Return current cart info
const getProducts: ProductsHandlers['getProducts'] = async ({
  res,
  body: { search, categories, category, brand, sort },
  config,
}) => {
  // Use a dummy base as we only care about the relative path
  const url = new URL('/v3/catalog/products', 'http://a')

  url.searchParams.set('is_visible', 'true')
  url.searchParams.set('limit', String(LIMIT))

  if (search) url.searchParams.set('keyword', search)

  if (category && Number.isInteger(Number(category))) {
    url.searchParams.set('categories:in', category)
  }

  if (
    categories &&
    categories.every((category: number) => Number.isInteger(Number(category)))
  )
    url.searchParams.set('categories:in', categories.join(','))

  if (brand && Number.isInteger(Number(brand)))
    url.searchParams.set('brand_id', brand)

  if (sort) {
    const [_sort, direction] = sort.split('-')
    const sortValue = SORT[_sort]

    if (sortValue && direction) {
      url.searchParams.set('sort', sortValue)
      url.searchParams.set('direction', direction)
    }
  }
```

I see where the query is being built, but am unsure how to use it on the client of the API. I have tried to follow the get `get` functions but feel like I am missing some key context to making this available to the client. I am assuming these are built to be running on the server since there is a `req, res` dependency in the arguments for the `createApiHandler` that is utilized later in the code.

What would be the best course of action to make this available to the client?
What are the purpose of handlers and how are they used?
What is the best practice for usage of handlers that currently exist in the code and export them as a hook on the client?
I would love some more context, as I would like to become a regular contributor to this library.

**Comment by jorgemasta** [comment]
Hey @kfroemming, I like the idea of allowing to send an array of categories instead of a single one 👍  

About using it on the client, I think it is a different issue. Feel free to open a new one if you see the need.

**Comment by jorgemasta** [comment]
It will be included in the next release
